fixed extra error message when game host is unreachable
triplea-game/triplea pull request #11101
Opened 2022-10-01 21:49 UTC by klarubbio

## Change Summary & Additional Notes

## Release Note

2022-10-01 21:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/triplea-game/triplea?pullRequest=11101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/triplea-game/triplea?pullRequest=11101) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/triplea-game/triplea?pullRequest=11101) it.</sub>

2022-10-01 23:02 UTC, beelee1 commented
Are you one of the iowa st guys ?

2022-10-02 23:08 UTC, RoiEXLab requested changes
This does not fix anything, and annotating `Optional` objects with `@Nullable` is bad practice!

2022-10-08 23:55 UTC, DanVanAtta commented
Most java annotations are stripped after compile time. As part of annotations, they indicate how they into the compilation phase they go (some can be retained even through runtime). `@Nullable` is only a hint for compilers & for developers, it has no impact on how the code operates at all. Hence, adding `@Nullable` annotations will not alter behavior. @RoiEXLab  has a good point that `Optional` values should never be null, their purpose is to avoid null values and to provide an API that is null-safe.

2022-10-08 23:55 UTC, closed without merging